// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "leenwood",
            "url": "https://github.com/leenwood/event-observability-platform"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/analytics/daily-events": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "Daily event statistics",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start date (YYYY-MM-DD)",
                        "name": "from",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "End date (YYYY-MM-DD, max 366 days range)",
                        "name": "to",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_leenwood_event-observability-platform_internal_analytics.DailyEventStat"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_http_handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_http_handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Liveness probe",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/ready": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Readiness probe",
                "responses": {
                    "200": {
                        "description": "ready",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "database unreachable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/webhooks/events": {
            "post": {
                "description": "Validates and deduplicates the request, persists the event to PostgreSQL,\nthen publishes it to the Kafka processing queue.\nDuplicate requests (same idempotency_key within TTL) return the original response.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "webhooks"
                ],
                "summary": "Ingest webhook event",
                "parameters": [
                    {
                        "description": "Webhook event payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_http_handler.webhookRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Duplicate — replayed from idempotency store (X-Idempotent-Replayed: true)",
                        "schema": {
                            "$ref": "#/definitions/internal_http_handler.webhookResponse"
                        }
                    },
                    "202": {
                        "description": "Event accepted for processing",
                        "schema": {
                            "$ref": "#/definitions/internal_http_handler.webhookResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid JSON",
                        "schema": {
                            "$ref": "#/definitions/internal_http_handler.errorResponse"
                        }
                    },
                    "415": {
                        "description": "Unsupported Content-Type",
                        "schema": {
                            "$ref": "#/definitions/internal_http_handler.errorResponse"
                        }
                    },
                    "422": {
                        "description": "Missing required fields",
                        "schema": {
                            "$ref": "#/definitions/internal_http_handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/internal_http_handler.errorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_leenwood_event-observability-platform_internal_analytics.DailyEventStat": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "event_count": {
                    "type": "integer"
                },
                "event_type": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                }
            }
        },
        "internal_http_handler.errorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "internal_http_handler.webhookRequest": {
            "type": "object",
            "properties": {
                "event_type": {
                    "type": "string"
                },
                "idempotency_key": {
                    "type": "string"
                },
                "payload": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "source": {
                    "type": "string"
                }
            }
        },
        "internal_http_handler.webhookResponse": {
            "type": "object",
            "properties": {
                "event_id": {
                    "type": "string"
                },
                "trace_id": {
                    "type": "string"
                }
            }
        }
    },
    "tags": [
        {
            "description": "Webhook ingestion endpoint",
            "name": "webhooks"
        },
        {
            "description": "ClickHouse-backed analytical queries",
            "name": "analytics"
        },
        {
            "description": "Liveness and readiness probes",
            "name": "health"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Event Observability Platform API",
	Description:      "Production-oriented webhook ingestion, async event processing, and analytics service.\n\nDemonstrates OpenTelemetry tracing, Prometheus metrics, Kafka pipelines,\nClickHouse analytics, idempotent processing, and circuit breaker patterns.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
