linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - dogsled
    - dupl
    - exhaustive
    - godot
    - nilerr
    - noctx
    - bodyclose
    - contextcheck
    - revive
    - gosec

linters-settings:
  revive:
    rules:
      - name: exported
        disabled: false
      - name: var-naming
        disabled: false
      - name: indent-error-flow
        disabled: false
  gosec:
    excludes:
      - G115
  dupl:
    threshold: 150
  exhaustive:
    default-signifies-exhaustive: true
  godot:
    scope: toplevel
    capital: false
  goimports:
    local-prefixes: github.com/leenwood/event-observability-platform

issues:
  exclude-rules:
    - path: "_test\\.go"
      linters:
        - dupl
        - gosec
    - path: "cmd/"
      linters:
        - revive
  max-issues-per-linter: 50
  max-same-issues: 5
